-- AlterTable
ALTER TABLE `WalletLedger` MODIFY `transactionType` ENUM('WALLET_TOPUP', 'ORDER_PAYMENT', 'WITHDRAWAL_REQUEST', 'WITHDRAWAL_RESERVED', 'WITHDRAWAL_PROCESSED', 'WITHDRAWAL_RELEASED', 'REFUND') NOT NULL;
